# -*- coding: utf-8 -*-
"""CS777_DataExtraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwCQJ6zLcROscEarsYIuDYhDx_9DXt42
"""

# GEOLIFE GPS Trajectories Analysis

from google.colab import drive
drive.mount('/content/drive')

import os
import json
from datetime import datetime

def convert_to_json(data_dir):
    trajectories = []
    for user_dir in os.listdir(data_dir):
        user_path = os.path.join(data_dir, user_dir, 'Trajectory')
        if os.path.isdir(user_path):
            for traj_file in os.listdir(user_path):
                traj_path = os.path.join(user_path, traj_file)
                with open(traj_path, 'r') as f:
                    lines = f.readlines()[6:]  # skip the first 6 lines of metadata
                    trajectory = []
                    for line in lines:
                        parts = line.strip().split(',')
                        point = {
                            "latitude": float(parts[0]),
                            "longitude": float(parts[1]),
                            "altitude": float(parts[3]),
                            "timestamp": datetime.strptime(parts[5] + ' ' + parts[6], '%Y-%m-%d %H:%M:%S')
                        }
                        trajectory.append(point)
                    trajectories.append({
                        "user_id": user_dir,
                        "trajectory": trajectory
                    })
    return trajectories

data_dir = "/content/drive/MyDrive/Colab Notebooks/Term Paper/Geolife Trajectories 1.3/Data"
trajectories = convert_to_json(data_dir)

# save the converted data to a JSON file
with open('geolife_trajectories.json', 'w') as f:
    json.dump(trajectories, f, indent=4, default=str)

print("Data conversion completed and saved to geolife_trajectories.json")

# save the converted data to a JSON file in Google Drive
output_file = '/content/drive/MyDrive/Colab Notebooks/Term Paper/Geolife Trajectories 1.3/geolife_trajectories.json'
with open(output_file, 'w') as f:
    json.dump(trajectories, f, indent=4, default=str)

print(f"Data conversion completed and saved to {output_file}")